import { systemPath } from "../tables/constants.js";

export const preloadHandlebarsTemplates = () => {
    foundry.applications.handlebars.loadTemplates([
        // Actor sheet cards
        systemPath("templates/actor/cards/armor.hbs"),
        systemPath("templates/actor/cards/item.hbs"),
        systemPath("templates/actor/cards/item/card-item-currency.hbs"),
        systemPath("templates/actor/cards/saves.hbs"),
        systemPath("templates/actor/cards/skill.hbs"),
        systemPath("templates/actor/cards/spell.hbs"),
        systemPath("templates/actor/cards/prepped-spell.hbs"),
        systemPath("templates/actor/cards/proficiency.hbs"),
        systemPath("templates/actor/cards/talent.hbs"),
        systemPath("templates/actor/cards/weapon.hbs"),

        // Actor sheet sections
        systemPath("templates/actor/parts/middle/base-middle.hbs"),
        systemPath("templates/actor/parts/middle/middle-abilities.hbs"),
        systemPath("templates/actor/parts/middle/middle-saves-l.hbs"),
        systemPath("templates/actor/parts/middle/middle-saves-r.hbs"),
        systemPath("templates/actor/parts/middle/middle-stats.hbs"),
        systemPath("templates/actor/parts/middle/middle-wounds.hbs"),
        systemPath("templates/actor/parts/beast-bio.hbs"),
        systemPath("templates/actor/parts/bio.hbs"),
        systemPath("templates/actor/parts/combat/base-combat.hbs"),
        systemPath("templates/actor/parts/combat/combat-armors.hbs"),
        systemPath("templates/actor/parts/combat/combat-weapons.hbs"),
        systemPath("templates/actor/parts/effects/base-effects.hbs"),
        systemPath("templates/actor/parts/header/base-header.hbs"),
        systemPath("templates/actor/parts/header/header-stats.hbs"),
        systemPath("templates/actor/parts/header/header-portrait.hbs"),
        systemPath("templates/actor/parts/inventory/base-inventory.hbs"),
        systemPath("templates/actor/parts/inventory/inventory-footer.hbs"),
        systemPath("templates/actor/parts/inventory/inventory-header.hbs"),
        systemPath("templates/actor/parts/inventory/inventory-list.hbs"),
        systemPath("templates/actor/parts/overview/base-overview.hbs"),
        systemPath("templates/actor/parts/overview/overview-skills.hbs"),
        systemPath("templates/actor/parts/spells/base-spells.hbs"),
        systemPath("templates/actor/parts/spells/spells-prepped.hbs"),
        systemPath("templates/actor/parts/spells/spells-library.hbs"),
        systemPath("templates/actor/parts/setup/base-setup.hbs"),
        systemPath("templates/actor/parts/setup/beast-base-setup.hbs"),
        systemPath("templates/actor/parts/setup/beast-setup-misc.hbs"),
        systemPath("templates/actor/parts/setup/beast-setup-yield.hbs"),
        systemPath("templates/actor/parts/setup/setup-abilities.hbs"),
        systemPath("templates/actor/parts/setup/setup-classes.hbs"),
        systemPath("templates/actor/parts/setup/setup-misc.hbs"),
        systemPath("templates/actor/parts/setup/setup-profs.hbs"),
        systemPath("templates/actor/parts/setup/setup-priors.hbs"),
        systemPath("templates/actor/parts/setup/setup-talents.hbs"),
        systemPath("templates/actor/parts/skills/base-skills.hbs"),

        // Chat cards
        systemPath("templates/chat/chat-alert.hbs"),
        systemPath("templates/chat/chat-attack.hbs"),
        systemPath("templates/chat/check.hbs"),
        systemPath("templates/chat/crit.hbs"),
        systemPath("templates/chat/chat-damage.hbs"),
        systemPath("templates/chat/chat-defend.hbs"),
        systemPath("templates/chat/initNote.hbs"),
        systemPath("templates/chat/fumble.hbs"),
        systemPath("templates/chat/chat-trauma.hbs"),
        systemPath("templates/chat/chat-save.hbs"),
        systemPath("templates/chat/chat-skill.hbs"),
        systemPath("templates/chat/chat-skill-survey.hbs"),
        systemPath("templates/chat/chat-spell.hbs"),

        systemPath("templates/item/parts/description.hbs"),
        systemPath("templates/item/parts/header-logistics.hbs"),
        systemPath("templates/item/parts/header.hbs"),

        systemPath("templates/dialog/ability-content-app.hbs"),
        systemPath("templates/dialog/getAttack.hbs"),
        systemPath("templates/dialog/cast.hbs"),
        systemPath("templates/dialog/critical-content-app.hbs"),
        systemPath("templates/dialog/fumble-content-app.hbs"),
        systemPath("templates/dialog/initiative-content-app.hbs"),
        systemPath("templates/dialog/getDamage.hbs"),
        systemPath("templates/dialog/defend.hbs"),
        systemPath("templates/dialog/getSave.hbs"),
        systemPath("templates/dialog/wound-content-app.hbs"),
        systemPath("templates/dialog/parts/getRollMode.hbs"),
        systemPath("templates/dialog/parts/getRollMode2.hbs"),

        systemPath("templates/dice/roll.hbs"),

        systemPath("templates/hud/waypoint-label.hbs"),
        systemPath("templates/hud/waypoint-label-subsection.hbs"),

        systemPath("templates/parts/tabulate.hbs"),

    ]);
};
